name: Build

on:
  push:
    branches:
      - master  # Trigger the action when code is pushed to the master branch
  pull_request:
    branches:
      - master  # Trigger the action on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      # Add other steps if needed, e.g., upload artifacts or deploy
